/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package akhir;

/**
 *
 * @author Irkhamnawan
 */
public class pilihan extends javax.swing.JInternalFrame {

    /**
     * Creates new form pilihan
     */
    public pilihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mhs = new javax.swing.JButton();
        dsn = new javax.swing.JButton();

        setTitle("DAFTAR SEBAGAI");

        mhs.setText("Mahasiswa");
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });

        dsn.setText("Dosen");
        dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(mhs)
                .addGap(82, 82, 82)
                .addComponent(dsn)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mhs)
                    .addComponent(dsn))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        signupMhs M = new signupMhs();
        M.setVisible(true);
        this.getDesktopPane().add(M);
        this.dispose();
    }//GEN-LAST:event_mhsActionPerformed

    private void dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsnActionPerformed
        signupDsn D = new signupDsn();
        D.setVisible(true);
        this.getDesktopPane().add(D);
        this.dispose();
    }//GEN-LAST:event_dsnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dsn;
    private javax.swing.JButton mhs;
    // End of variables declaration//GEN-END:variables
}
